USE [master]
GO

/****** Object:  Database [kariyerimDB]    Script Date: 19.09.2025 16:38:25 ******/
CREATE DATABASE [kariyerimDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kariyerimDB', FILENAME = N'C:\Users\sefik\kariyerimDB.mdf' , SIZE = 65536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kariyerimDB_log', FILENAME = N'C:\Users\sefik\kariyerimDB_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kariyerimDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kariyerimDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kariyerimDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kariyerimDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kariyerimDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kariyerimDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [kariyerimDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kariyerimDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kariyerimDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kariyerimDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kariyerimDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kariyerimDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kariyerimDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kariyerimDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kariyerimDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kariyerimDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kariyerimDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kariyerimDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kariyerimDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kariyerimDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kariyerimDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kariyerimDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kariyerimDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kariyerimDB] SET RECOVERY FULL 
GO

ALTER DATABASE [kariyerimDB] SET  MULTI_USER 
GO

ALTER DATABASE [kariyerimDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kariyerimDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kariyerimDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kariyerimDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [kariyerimDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kariyerimDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [kariyerimDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [kariyerimDB] SET  READ_WRITE 
GO

